### ISSUE TITLE
Sugestion: faker Image

### ISSUE THREAD

**Issue by igorgoncalves** [drager/faker#19]
Based on Faker for PHP, the Image provider get images from [lorem pixel](http://lorempixel.com/) or [unplash](https://source.unsplash.com/) to dowload images by categories.

Other alternative is [place kitten](https://placekitten.com/) but only for cats photos.

Exemple img URL: 
**Lorem Pixel:** [http://lorempixel.com/800/600/](http://lorempixel.com/800/600/)
**Unplash:** [https://source.unsplash.com/1600x900/?nature,water](https://source.unsplash.com/1600x900/?nature,water)

Faker PHP repository(use lorem pixel):  [https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Image.php](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Image.php)
Faker JS repository (use unplash): [https://github.com/Marak/faker.js/blob/master/lib/image.js](https://github.com/Marak/faker.js/blob/master/lib/image.js)

**Comment by drager** [comment]
@igorgoncalves Sounds good! Feel free to send a PR

**Comment by igorgoncalves** [comment]
Nice! Working in it :dancer:

**Comment by drager** [comment]
Fixed in #21
