### ISSUE TITLE
Faker generating invalid email addresses

### ISSUE THREAD

**Issue by bobjackman** [drager/faker#2]
It looks like `faker.internet.email()` is generating its result by calling `domainName()`, which in turn calls `domainWord()`, which in turn uses a random element from `lastNames`. Some of those last names have special characters that are illegal in email addresses (and domain names). e.g. `teresa_buckridge@d'amore.info` was the latest offender I generated.

I think it's good to have special characters in faker data to make sure our systems can properly handle them, but they need to be limited to places where special characters are legal to begin with.

###### [lib/src/internet.dart](https://github.com/drager/faker/blob/master/lib/src/internet.dart#L81)
```patch
-  String domainWord() => random.element(lastnames).toLowerCase()
+  String domainWord() => random
+    .element(lastnames)
+    .toLowerCase()
+    .replaceAll(new RegExp(r'[^a-z0-9\-]'), ''); // -- remove illegal domain characters
```

**Comment by drager** [comment]
Fixed in #3.
