### ISSUE TITLE
Sugestion: seed for random generator

### ISSUE THREAD

**Issue by fflori4n** [drager/faker#25]
Currently I don't see if there is a way to set a seed for the random generator. Something like in the python library 'faker' would be nice:

from faker import Faker
fake = Faker()
Faker.seed(4321)

Can't seem to find if the Random() function has a method to set it's seed?

**Comment by drager** [comment]
Sounds like a good suggestion. Feel free to send a PR :blush:

**Comment by daemon3000** [comment]
@drager Is it ok if I open another PR for this? There hasn't been any activity on the previous one.

**Comment by fflori4n** [comment]
Go ahead. This pull request used an older fork, so it won't be merged, and I forgot to make a new one. Sorry. The code to solve the issue is in there, so use it if you want to.

**Comment by drager** [comment]
> @drager Is it ok if I open another PR for this? There hasn't been any activity on the previous one.

Yes, feel free to do that!

**Comment by drager** [comment]
Fixed in #32
