### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by ivanthz** [drager/faker#42]
I'll submit a function to generate fake jwt. Today I use like internal function, but I think this is a useful function. What do you say?

There's just one thing, this function needs "crypto" package of dev.dart. Is this a problem?

**Comment by drager** [comment]
Hey! Sounds like a nice function to have in this package.

I don't think that's a problem. Will look at the PR. Thanks!

**Comment by drager** [comment]
Fixed in #43

**Comment by drager** [comment]
Released in [2.0.0-rc-2](https://pub.dev/packages/faker/versions/2.0.0-rc.2)
