### ISSUE TITLE
Make it null safe

### ISSUE THREAD

**Issue by Abhishek0116** [drager/faker#47]
### Make this package null-safe.

**Comment by drager** [comment]
Hello! :wave: Did you try out the rc? https://pub.dev/packages/faker/versions/2.0.0-rc.2

**Comment by Abhishek0116** [comment]
@drager Thanks.

> Hello! 👋 Did you try out the rc? https://pub.dev/packages/faker/versions/2.0.0-rc.2

Your suggested pre-release version is fine for now so I am closing the issue. Hope you will release it as stable soon.
