### ISSUE TITLE
1 positional argument(s) expected, but 0 found. Try adding the missing arguments

### ISSUE THREAD

**Issue by Chris-Imade** [drager/faker#51]
Just a few lines in my code, I am a complete beginner...trying to follow along a tutorial and I get that error.
This is all I have in my code
![code snippet](https://user-images.githubusercontent.com/68008022/139839961-420c534b-52bd-4abf-b51f-68554a5d455c.PNG)

**Comment by klevar-jeph** [comment]
Please I need help with this thanks...in advance

**Comment by klevar-jeph** [comment]
OK I guess I figured out what the problem was. So just in case someone else got stuck with the same problems.
I called faker on the faker object and that was it.


![code snippet2](https://user-images.githubusercontent.com/68008022/139842645-62b6c682-1042-480f-bc13-0a77e1e46e81.PNG)
